# Generated by Django 2.0.7 on 2018-08-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('verified_flag', models.BooleanField()),
                ('rejected_flag', models.BooleanField()),
            ],
        ),
    ]
